-- ====================================================================
-- Qwen Image Editor - Complete Database Initialization Script
-- Compatible with: Supabase, Neon, Vercel Postgres, AWS RDS
-- ====================================================================

-- 1. User Info Table
CREATE TABLE IF NOT EXISTS user_info (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    user_id VARCHAR UNIQUE,
    name VARCHAR,
    email VARCHAR UNIQUE,
    image VARCHAR,
    last_login_ip VARCHAR
);

-- 2. User Available Credits Table
CREATE TABLE IF NOT EXISTS user_available (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    user_id VARCHAR UNIQUE,
    stripe_customer_id VARCHAR,
    available_times INTEGER DEFAULT 2
);

-- 3. Stripe Customers Table
CREATE TABLE IF NOT EXISTS stripe_customers (
    user_id VARCHAR NOT NULL PRIMARY KEY,
    stripe_customer_id TEXT
);

-- 4. Stripe Subscriptions Table
DO $$ BEGIN
    CREATE TYPE subscription_status AS ENUM (
        'trialing', 'active', 'canceled', 'incomplete', 'incomplete_expired', 'past_due', 'unpaid', 'paused'
    );
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

CREATE TABLE IF NOT EXISTS stripe_subscriptions (
    id TEXT NOT NULL PRIMARY KEY,
    user_id VARCHAR,
    status subscription_status,
    metadata JSONB,
    price_id TEXT,
    quantity INTEGER,
    cancel_at_period_end BOOLEAN,
    created TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    current_period_start TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    current_period_end TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    ended_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
    cancel_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
    canceled_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
    trial_start TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
    trial_end TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 5. Works / Generations Table
CREATE TABLE IF NOT EXISTS works (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    uid VARCHAR UNIQUE,
    input_text VARCHAR,
    revised_text VARCHAR,
    output_url VARCHAR,
    input_image_url VARCHAR,
    task_type VARCHAR DEFAULT 'text2img',
    is_public BOOLEAN DEFAULT false,
    status INTEGER DEFAULT 1,
    user_id VARCHAR,
    is_origin BOOLEAN DEFAULT true,
    origin_language VARCHAR DEFAULT 'en',
    current_language VARCHAR DEFAULT 'en',
    is_delete BOOLEAN DEFAULT false
);

-- 6. Key Value Store Table (for Stripe idempotency)
CREATE TABLE IF NOT EXISTS key_value (
    key VARCHAR NOT NULL PRIMARY KEY,
    value VARCHAR
);

-- 7. Search Logs Table
CREATE TABLE IF NOT EXISTS search_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    search_text VARCHAR,
    result_count VARCHAR,
    user_agent VARCHAR,
    search_ip VARCHAR
);

-- 8. Sensitive Words Table
CREATE TABLE IF NOT EXISTS sensitive_words (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    words VARCHAR NOT NULL,
    level VARCHAR DEFAULT '1'
);

-- Create Indexes for Optimal Performance
CREATE INDEX IF NOT EXISTS idx_works_uid ON works(uid);
CREATE INDEX IF NOT EXISTS idx_works_user_id ON works(user_id);
CREATE INDEX IF NOT EXISTS idx_works_created_at ON works(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_user_info_user_id ON user_info(user_id);
CREATE INDEX IF NOT EXISTS idx_user_info_email ON user_info(email);
CREATE INDEX IF NOT EXISTS idx_user_available_user_id ON user_available(user_id);
